### ISSUE TITLE
Link to training data isn't working

### ISSUE THREAD

**Issue by skwalker** [wukevin/babel#12]
Hi,

I'm trying to reproduce the pre-trained model, using the relevant training data, but the link provided in the README isn't working for me. 

Thanks!
Sarah

**Comment by wukevin** [comment]
We've updated the data download to add a mirror to Google Drive; see https://drive.google.com/file/d/1J-4HH5e8rYapq5JtRq7G-foDs6Y9NzyQ/view?usp=share_link and the updated `README.md` - thanks!
