### ISSUE TITLE
Conda environment package conflicts

### ISSUE THREAD

**Issue by sannalda** [wukevin/babel#13]
#6 

Hi! I am trying to use the environment file (environment2.yml), but I think its a bit outdated (there are package conflicts). I've been able to reconstruct a new environment that works, but if you have an updated environment that would great :)

[babel_env_updated.txt](https://github.com/wukevin/babel/files/11968572/babel_env_updated.txt)

**Comment by wukevin** [comment]
Thanks for bringing this up; we've provided an updated environment in `environment_minimal.yml`. There are some packages that must remain outdated due to changes in API.
