### ISSUE TITLE
predict_model error

### ISSUE THREAD

**Issue by myylee** [wukevin/babel#8]
Hi Kevin, 

Thanks for the great package. I encountered this error when running the predict_model.py file. Similar error happened when I try to run prediction function such as translate_1_to_1, or do_evaluation_rna_from_rna. 
Would greatly appreciate it if you could give some insight into what might be causing the error. Thanks in advance! 
![image](https://user-images.githubusercontent.com/66084077/144685385-c508a612-2cca-46ac-8e9a-874707bf2484.png)

Best regards,
Michelle

**Comment by myylee** [comment]
Nevermind, I solved it by reinstalling the babel environment using the environment.txt you shared in the other issue. Thanks anyways!

Best regards,
Michelle

**Comment by wukevin** [comment]
Hi Michelle, are you referring to the environment.txt from https://github.com/wukevin/babel/issues/6 as the one that solved the issue?

**Comment by myylee** [comment]
Yes.
